[package]
name = "cb2"
version = "0.1.0"
authors = ["Shane Osbourne <shane.osbourne8@gmail.com>"]
edition = "2018"

[dependencies]
cb2_core = { path = "../cb2_core" }
env_logger = "0.6.0"
log = "0.4.6"
futures = "0.1.25"
tokio = "0.1.13"
ansi_term = "0.11.0"
